name: Documentation
on: workflow_dispatch
jobs:
  generate-documentation:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - name: Install NPM packages
        run: npm ci
      - name: Generate documentation
        run: npm run docs
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add docs
          git commit -m "Updated documentation"
      - name: Push changes
        uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
