name: Package
on:
  workflow_run:
    workflows:
     - Tests
    branches:
      - main
    types:
      - completed
      - requested
jobs:
  deploy-packages:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
