name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run linter
        run: yarn lint
      - name: Run tests with coverage report
        run: yarn coverage
      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["aion-dk/build-and-push-action@v1.0.6"]'
          checkout_base_path: ./.github/actions
          ssh_private_key: ${{ secrets.PUBLIC_PROJECT_PRIVATE_REPO_ACCESS_KEY }}

      - name: "Build and push docker image"
        uses: ./.github/actions/build-and-push-action
        with:
          image_name: js-client
          ecr_access_key_id: ${{ secrets.AWS_RW_ACCESS_KEY_ID }}
          ecr_secret_key: ${{ secrets.AWS_RW_SECRET_KEY }}
