name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Install NPM packages
        run: npm ci
      - name: Run tests with coverage report
        run: npm run coverage
      - name: Generate code coverage badge and commit it
        if: success() && github.ref == 'refs/heads/main'
        run: |
          set -x
          coverage_percentage=`cat coverage/coverage-summary.json | jq '.total.lines.pct'`
          curl "https://img.shields.io/badge/coverage-$coverage_percentage%25-blue" > .github/coverage_badge.svg
          if git status | grep coverage_badge.svg; then
            echo 'Coverage changed'
            git config --local user.email "action@github.com"
            git config --local user.name "Github Action"
            git add .github/coverage_badge.svg
            git commit -m "Updated coverage badge"
          else
            echo 'Coverage remains the same'
          fi
      - name: Push committed coverage badge
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
